Traceback (most recent call last):
  File "e:\ATF\ATF\AdaptoFlux.py", line 679, in training
    self.history_method_inputs.pop()
                 ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'rollback_count' where it is not associated with a value
